route01 = ['ADAJAN GSRTC',
'JILANI BRIDGE APPROACH KATARGAM',
'KATARGAM DARWAJA BRT',
'GOTALAWADI',
'KABIR MANDIR RAMPURA',
'LAL DARWAJA',
'RAILWAY STATION TERMINAL',
'LINEAR BUS STOP',
'GOLDEN POINT',
'SAHARA DARWAJA',
'TEXTILE MARKET',
'KAMELA DARWAJA',
'KINNARY CINEMA',
'MAAN DARWAJA',
'UDHANA DARWAJA BRTS',
'KHARWARNAGAR BRTS',
'SUB JAIL',
'NEW CIVIL HOSPITAL',
'MAJURA GATE',
'GANDHI COLLEGE',
'VANITA VISHRAM GROUND',
'ATHWAGATE',
'SWAMINARAYAN CHOWK BRTS',
'ADAJAN PATIYA BRTS',
'ADAJAN GSRTC']

route02 = ['ADAJAN GSRTC',
'ADAJAN PATIYA BRTS',
'SWAMINARAYAN CHOWK BRTS',
'ATHWAGATE',
'VANITA VISHRAM GROUND',
'GANDHI COLLEGE',
'MAJURA GATE',
'NEW CIVIL HOSPITAL',
'SUB JAIL',
'UDHANA DARWAJA BRTS',
'KHARWARNAGAR BRTS',
'MAAN DARWAJA',
'KINNARY CINEMA',
'KAMELA DARWAJA',
'TEXTILE MARKET',
'SAHARA DARWAJA',
'GOLDEN POINT',
'LINEAR BUS STOP',
'RAILWAY STATION TERMINAL',
'LAL DARWAJA',
'KABIR MANDIR RAMPURA',
'GOTALAWADI',
'GOTALAWADI',
'KATARGAM DARWAJA BRT',
'JILANI BRIDGE APPROACH KATARGAM',
'ADAJAN GSRTC']

route11 = ['UDHANA DARWAJA BRTS',
'KHARWARNAGAR BRTS',
'SATYANAGAR BRTS',
'UDHANA TEEN RASTA BRTS',
'UDHANA GSRTC BRTS',
'UDHANA ACADEMY COLLEGE BRTS',
'LAXMI NARAYAN TEMPLE BRTS',
'DAKSHESHWAR MAHADEV BRTS',
'PANDESARA GIDC BRTS',
'KAMNATH MAHADEV BRTS',
'NAVIN FLUORINE BRTS',
'BHESTAN NAHER BRTS',
'BHAGWATINAGAR INDUSTRIAL ESTATE BRTS',
'UNN NAKA BRTS',
'UNN INDUSTRIAL ESTATE BRTS',
'UNN CHAR RASTA BRTS',
'GREEN PARK BRTS',
'SACHIN GIDC JUNCTION BRTS']

route12 = ['ONGC Colony BRTS',
'Magdalla Gam BRTS',
'‘Y’ Junction Dumas Road BRTS',
'‘Y’ Junction Udhana Magdalla Road BRTS',
'Maharana Pratap Junction BRTS',
'S.D. Jain School BRTS',
'J.H. Ambani School BRTS',
'Someshwar Junction BRTS',
'VNSG University',
'V.N.S.G.U. Convention Hall BRTS',
'Centre for Social Studies BRTS',
'Anuvrat Dwar Junction (West) BRTS',
'Anuvrat Dwar Junction (East) BRTS',
'Panas Gam Junction BRTS',
'Ishwar Farm Junction BRTS',
'Jamna Nagar Junction BRTS',
'Rupali Junction BRTS',
'Prajapita Brahmakumari Marg BRTS',
'Unique Hospital Junction BRTS',
'Khatodara GIDC BRTS',
'Kharwarnagar BRTS',
'Kharwar Nagar Creek',
'Bhathena Junction BRTS',
'Samrat Vidhyalaya BRTS',
'Model Town Junction BRTS',
'Parvat Patiya Junction BRTS',
'Amazia Amusement Park BRTS',
'Vishwakarma Junction BRTS',
'Bhaiya Nagar BRTS',
'Punagam Junction BRTS',
'Puna Saroli Junction BRTS',
'Vanmali Junction (West) BRTS',
'Vanmali Junction BRTS',
'Simada Naher Junction BRTS',
'Simada Junction BRTS',
'Yogi Nagar BRTS',
'Swagat Society BRTS',
'S.M.V.S. Swaminarayan Temple BRTS',
'Sarthana Nature Park BRTS']

route13 = ['KADODARA',
'VARELI GAAM',
'ANTROLI',
'SABAR GAAM',
'KUMBHARIYA GAAM',
'SAROLI BRTS',
'CANCER HOSPITAL BRTS',
'VISHWAKARMA MANDIR BRTS',
'BHAKTI DHAM BRTS',
'MAGOB GAM BRT',
'AMAZIA AMUSEMENT PARK BRTS',
'SITANAGAR BRTS',
'ANJANI BOOT BHAVANI ROAD BRTS',
'LAMBE HANUMAN ROAD BRTS',
'RACHANA CIRCLE',
'D.G.V.C.L. URJA SADAN BRTS',
'HIRABAUG BRTS',
'VALLABHACHARYA ROAD BRTS',
'SHREE SWAMINARAYAN MANDIR RUSTOM BAUG BRTS',
'FULPADA ROAD BRTS',
'GAJERA CIRCLE BRTS',
'S.M.C. NORTH ZONE (KATARGAM) OFFICE BRTS',
'HARE KRISHNA CIRCLE / LALITA CHOKADI BRTS',
'BAPA SITARAM CHOWK BRTS',
'SHREE SAHJANAND CHOWK BRTS',
'S.M.V.S. SWAMINARAYAN TEMPLE (DABHOLI) BRTS',
'DABHOLI GAM BRTS',
'DR. SHYAMAPRASAD MUKHARJI BRIDGE BRTS',
'JAHANGIRPURA COMMUNITY HALL BRTS']

route14 = ['ONGC COLONY BRTS',
'MAGDALLA GAM BRTS',
'Y JUNCTION DUMAS ROAD BRTS',
"MAGDALLA 'T' JUNCTION BRTS",
'RUNDHNATH MAHADEV MANDIR BRTS',
'GOVERDHAN NATHJI HAVELI BRTS',
"LANCER'S ARMY SCHOOL BRTS",
'PIPLOD BRTS',
'KARGIL CHOWK BRTS',
'S.V.N.I.T. BRTS',
'UMRA GAAM BRTS',
'PAL R.T.O. BRTS',
'SANJEEV KUMAR AUDITORIUM BRTS',
'ADAJAN GAM BRTS',
'ANAND MAHAL ROAD BRTS',
'SWAMINARAYAN CHOWK BRTS',
'ADAJAN PATIYA BRTS',
'SHANKHESHWAR CHOWK BRTS',
'NAVYUG COLLEGE BRTS',
'S.M.C. WEST ZONE OFFICE BRTS',
'TADWADI BRTS',
'PALANPUR PATIYA BRTS',
'RAMNAGAR BRTS',
'MORABHAGAL BRTS',
'JAHANGIRPURA COMMUNITY HALL BRTS',
'DR. SHYAMAPRASAD MUKHARJI BRIDGE BRTS',
'DABHOLI GAM BRTS',
'S.M.V.S. SWAMINARAYAN TEMPLE (DABHOLI) BRTS',
'SHREE SAHJANAND CHOWK BRTS',
'BAPA SITARAM CHOWK BRTS',
'HARE KRISHNA CIRCLE / LALITA CHOKADI BRTS',
'S.M.C. NORTH ZONE (KATARGAM) OFFICE BRTS',
'GAJERA CIRCLE BRTS',
'PANDIT SHYAMJI KRISHNA VERMA BRIDGE BRTS',
'AMROLI CHAR RASTA',
'AMROLI CROSS ROAD',
'KOSAD FIRE STATION BRTS',
'KOSAD HOUSING BOARD BRTS',
'KOSAD DEPOT BRTS',
'KOSAD EWS H1 BRTS',
'KOSAD EWS H2 BRTS']

route15 = ['SOMESHWAR JUNCTION BRTS',
'V.N.S.G. UNIVERSITY BRTS',
'V.N.S.G.U. CONVENTION HALL BRTS',
'CENTRE FOR SOCIAL STUDIES BRTS',
'ANUVRAT DWAR JUNCTION (WEST) BRTS',
'ANUVRAT DWAR JUNCTION (EAST) BRTS',
'PANAS GAM JUNCTION BRTS',
'ISHWAR FARM JUNCTION BRTS',
'JAMNA NAGAR JUNCTION BRTS',
'RUPALI JUNCTION BRTS',
'PRAJAPITA BRAHMAKUMARI MARG BRTS',
'UNIQUE HOSPITAL JUNCTION BRTS',
'KHATODARA GIDC BRTS',
'KHARWARNAGAR BRTS',
'KHARWARNAGAR CREEK BRTS',
'BHATHENA JUNCTION BRTS',
'SAMRAT VIDHYALAYA BRTS',
'MODEL TOWN JUNCTION BRTS',
'PARVAT PATIYA JUNCTION BRTS',
'AMAZIA AMUSEMENT PARK BRTS',
'PUNA CANAL BRTS',
'MAGOB PARVAT KHADI BRIDGE BRTS',
'PARVAT GAM BRTS',
'DEVADH GAM ROAD BRTS',
'JAI JOGANI MATA CHOWK BRTS',
'FAASPAS DADA TEMPLE BRTS',
'MANGAL PANDEY HALL BRTS',
'MAHARANA PRATAP BRIDGE BRTS',
'DINDOLI KHARWASA ROAD BRTS',
'DINDOLI VARIGRUH BRTS',
'PANDESARA GIDC BRTS',
'TULSIDHAM BRTS',
'CHIKUWADI BRTS',
'PATRAKAR COLONY BRTS',
'KAILASH NAGAR BRTS',
'PANCHMUKHI HANUMAN MANDIR BRTS',
'ALTHAN KHADI BRTS',
'ALTHAN CANAL BRTS',
'SHYAM MANDIR BRTS',
'ALTHAN BHARTHANA BRTS',
'BHARTHANA BRTS',
'CHINAGATE BRTS',
'ANUVRAT DWAR JUNCTION (WEST) BRTS',
'CENTRE FOR SOCIAL STUDIES BRTS',
'V.N.S.G.U. CONVENTION HALL BRTS',
'V.N.S.G. UNIVERSITY BRTS',
'SOMESHWAR JUNCTION BRTS']

route16 = ['Gajera Circle BRTS',
'Fulpada Road BRTS',
'Shree Swaminarayan Mandir Rustom Baug BRTS',
'Vallabhacharya Road BRTS',
'Hirabaug BRTS',
'D.G.V.C.L. Urja Sadan BRTS',
#'S.M.C. Kapodara Ward Office BRTS',
'Lambe Hanuman Road BRTS',
'Anjani Boot Bhavani Road BRTS',
'Sitanagar BRTS',
'Amazia Amusement Park BRTS',
'Magob Gam BRTS',
'Magob Parvat Khadi Bridge BRTS',
'Parvat Gam BRTS',
'Devadh Gam Road BRTS',
'Jai Jogani Mata Chowk BRTS',
'Aaspas Dada Temple BRTS',
'Mangal Pandey Hall BRTS',
'Maharana Pratap Bridge BRTS',
'Dindoli Kharwasa Road BRTS',
'Dindoli Varigruh BRTS']

route17 = ['Kamrej Terminal BRTS',
'Shyam Nagar BRTS',
'Pasodara Gam BRTS',
'Diamond Vidhya Sankul BRTS',
'Diamond Nagar BRTS',
'DGVCL Laskana BRTS',
'Laskana Gam BRTS',
'Raghuvir Row House BRTS',
'Valak Gam BRTS',
'Sagwadi BRTS',
'Shyamdham Mandir BRTS',
'Purushottam Nagar BRTS',
'Sarthana Nature Park BRTS',
'Maharana Pratap Garden (Chowpati) BRTS',
'Nana Varachha Vari Gruh BRTS',
'Kapodara Fire Station BRTS',
'S.M.C. Kapodara Ward Office BRTS',
'D.G.V.C.L. Urja Sadan BRTS',
'Shrimad Vallabhacharya Chowk BRTS',
'Baroda Pristage BRTS',
'Maangadh Chowk BRTS',
'Central Ware House BRTS',
# 'S.M.C. Varachha Health Centre BRTS',
# 'Railway Station Terminal',
# 'Patelwadi',
# 'Gotalawadi',
'Katargam Darwaja BRTS',
'Jilani Bridge Approach Katargam',
'Adajan Patiya BRTS',
'Swaminarayan Chowk BRTS',
'Anand Mahal Road BRTS',
'Adajan Gam BRTS',
'Sanjeev Kumar Auditorium BRTS',
'Pal R.T.O. BRTS']

route17e = ['Kamrej Terminal BRTS',
'Sarthana Nature Park BRTS',
'D.G.V.C.L. Urja Sadan BRTS',
'Shrimad Vallabhacharya Chowk BRTS',
'Baroda Pristage BRTS',
'Maangadh Chowk BRTS',
'Central Ware House BRTS',
'S.M.C. Varachha Health Centre BRTS',
'Railway Station Terminal',
'Linear Bus Stop',
'Golden Point',
'Sahara Darwaja',
'Udhana Darwaja',
'Kharwarnagar BRTS',
'Udhana Teen Rasta BRTS',
'Udhana Academy College BRTS',
'Pandesara GIDC BRTS',
'Unn Industrial Estate BRTS',
'Sachin GIDC Junction']

route18 = ['Utran R.O.B. Bridge BRTS',
'Shree Swami Dayanand Saraswati Bridge',
'S.M.C. Kapodara Ward Office BRTS',
'D.G.V.C.L. Urja Sadan BRTS',
'Shrimad Vallabhacharya Chowk BRTS',
'Baroda Pristage BRTS',
'Maangadh Chowk BRTS',
'Central Ware House BRTS',
'S.M.C. Varachha Health Centre BRTS',
'Railway Station Terminal']

route19 = ['RAILWAY STATION TERMINAL',
'LINEAR BUS STOP',
'GOLDEN POINT',
'SAHARA DARWAJA',
'SMIMER HOSPITAL BRT',
'APMC SARDAR MARKET BRTS',
'AAI MATA CHOWK BRTS',
'SHREE SANT KHETESHWAR CIRCLE BRTS',
'AMAZIA AMUSEMENT PARK BRTS',
'PUNA CANAL BRTS',
'BHAKTI DHAM BRTS',
'VISHWAKARMA MANDIR BRTS',
'CANCER HOSPITAL BRTS',
'SAROLI BRTS',
'KUMBHARIYA GAAM',
'SABAR GAAM',
'ANTROLI',
'VARELI GAAM',
'KADODARA']

route20 = ['KOSAD EWS H2 BRTS',
'KOSAD EWS H1 BRTS',
'KOSAD HOUSING BOARD BRTS',
'KOSAD FIRE STATION BRTS',
'AMROLI CROSS ROAD',
'AMROLI CHAR RASTA',
'PANDIT SHYAMJI KRISHNA VERMA BRIDGE BRTS',
'GAJERA CIRCLE BRTS',
'DR. SHYAMAPRASAD MUKHARJI LAKE GARDEN BRTS',
'KATARGAM BRT',
'KATARGAM DARWAJA BRT',
'GOTALAWADI',
'KABIR MANDIR RAMPURA',
'RAILWAY STATION TERMINAL',
'LINEAR BUS STOP',
'GOLDEN POINT',
'SAHARA DARWAJA',
'UDHANA DARWAJA BRTS',
'KHARWARNAGAR BRTS']

route21 = ['JAHANGIRPURA COMMUNITY HALL BRTS',
'MORABHAGAL BRTS',
'RAMNAGAR BRTS',
'PALANPUR PATIYA BRTS',
'TADWADI BRTS',
'S.M.C. WEST ZONE OFFICE BRTS',
'NAVYUG COLLEGE BRTS',
'SHANKHESHWAR CHOWK BRTS',
'JILANI BRIDGE APPROACH KATARGAM',
'KATARGAM DARWAJA BRT',
'GOTALAWADI',
'KABIR MANDIR RAMPURA',
'RAILWAY STATION TERMINAL',
'LINEAR BUS STOP',
'GOLDEN POINT',
'SAHARA DARWAJA',
'SMIMER HOSPITAL BRT',
'APMC SARDAR MARKET BRTS',
'AAI MATA CHOWK BRTS',
'SHREE SANT KHETESHWAR CIRCLE BRTS',
'MAGOB GAM BRT',
'MAGOB PARVAT KHADI BRIDGE BRTS',
'PARVAT GAM BRTS',
'DEVADH GAM ROAD BRTS',
'JAI JOGANI MATA CHOWK BRTS',
'AASPAS DADA TEMPLE BRTS',
'MANGAL PANDEY HALL BRTS',
'MAHARANA PRATAP BRIDGE BRTS',
'DINDOLI KHARWASA ROAD BRTS',
'DINDOLI VARIGRUH BRTS',
'PANDESARA GIDC BRTS']

route22 = ['KOSAD EWS H2 BRTS',
'KOSAD EWS H1 BRTS',
'KOSAD HOUSING BOARD BRTS',
'KOSAD FIRE STATION BRTS',
'AMROLI CROSS ROAD',
'AMROLI CHAR RASTA',
'UTRAN R.O.B. BRIDGE BRTS',
'SHREE SWAMI DAYANAND SARASWATI BRIDGE',
'D.G.V.C.L. URJA SADAN BRTS',
'S.M.C. KAPODARA WARD OFFICE BRTS',
'KAPODARA FIRE STATION BRTS',
'NANA VARACHHA VARI GRUH BRTS',
'MAHARANA PRATAP GARDEN (CHOWPATI) BRTS',
'NANA VARACHHA POLICE STATION BRTS',
'SARTHANA NATURE PARK BRTS']

route102 = ['Railway Station Terminal',
'Delhi Gate',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',    
'Bhagal Char Rasta',
'Kot Safil Road',
'Wadi Faliya',   
'Kot Safil Road  ',
'Bhagal Char Rasta  ',
'Bhajiwali Pol',   
'Kaskiwad',    
'Saiyedpura Vegetable Market',
'Pumping Char Rasta',  
'Hodi Bungalow',   
'Katargam Darwaja BRT',
'Katargam Police Station  ',
'Bal Ashram',   
'Katargam Fire Station  ',
'Katargam',    
'Kantareshwar Mahadev   ',
'Lalita Circle',   
'Bapa Sitaram Chowk BRTS ',
'Shree Sahjanand Chowk BRTS ',
'Dabholi Char Rasta',  
'Pramukh Swamy Chowk  ',
'S M C Health Club',
'Nani Ved',   
'Swami Narayan Gurukul  ',
'Moti Ved Dargah',  
'Moti Ved']
    
route103V = ['Lambe Hanuman Temple',
'J.B. Diamond',
'Vasant Bikha Ni Wadi',
'Matawadi Chowk',
'Laabheshwar Chowk',
'Ghanshyam Nagar',
'Santosh Nagar',
'Rachna Circle',
'Rachana Society',
'D.G.V.C.L. Urja Sadan BRTS',
'Shree Swami Dayanand Saraswati Bridge',
'Utran Power House',
'Samata Nagar',
'Mota Varachha Pumping Station',
'Apple Heights',
'Sudama Chowk',
'Mota Varachha Fire Station',
'Mota Varachha Ward Office',
'Mota Varachha Prathmik School',
'Mota Varachha Lake',
'Anand Dhara Society Mota Varachha',
'Kakrapar Canal Road',
'Gothan Bridge',
'Kiran Residency',
'Umra Naka',
'Shiv Park Residency',
'Bapa Sitaram Petrol Pump',
'Saurashtra Green City',
'Madhuvan Public School Approach',
'Avshar Bungalow',
'Pranam Residency',
'Rangoli Chokadi',
'Velanja Gaam',
'Ramvatika Society']

route104 = ['Railway Station Terminal',
'Linear Bus Stop',
'Golden Point',
'Sahara Darwaja',
'Textile Market',
'Kamela Darwaja',
'Halpati Colony',
'Bhathena Canal Junction',
'Siddhi Vinayak Temple',
'Khodiyarnagar',
'L.N. Park Society',
'Udhana GIDC Mahatma Gandhi Road',
'Udhana Railway Station',
'ROAD No. 3 UDHANA UDHYOG',
'NAGAR CHAR RASTA',
'Udhana Road No.6 Junction',
'S.M.C. Sankul',
'Umiya Nagar',
'Laxminagar Society',
'Dindoli Gam',
'Jitesh Park Society',
'Millenium Park',
'Vrukshlaxmi Society']

route105 = ['Railway Station Terminal',
'Linear Bus Stop',
'Golden Point',
'Sahara Darwaja',
'Textile Market',
'Kamela Darwaja',
'Kinnary Cinema',
'Maan Darwaja',
'Sub Jail',
'Khatodara Wadi',
'Khatodara GIDC',
'Sosyo Circle',
'Gandhi Kutir',
'Sickon Circle',
'Ashapura Mata Mandir',
'Umabhavan',
'Vishnu Nagar',
'Piyush Complex',
'Patrakar Colony BRTS',
'Pandesara',
'SMC Community Hall Pandesara',
'Bhagirath Apartment',
'KV Hagrenad Road',
'G-Tex Prints',
'Vitrag Chemical',
'Colourtex',
'Alfa Way Bridge Chokdi',
'Pandesara Industries Estate',
'Pandesara GIDC BRTS',
'Tulsidham BRTS',
'Chikuwadi BRTS']

route105G = ['Chowk Terminal',
'Machhiwad',
'Kuvawadi',
'Man Mandir Apartment',
'Mahavir Hospital',
'Gandhi College',
'Majura Gate',
'Majuragate Civil Hospital',
'Income Tax',
'Kapadia Health Club',
'Prajapita Brahmakumari Marg BRTS',
'Unique Hospital Junction BRTS',
'Sosyo Circle',
'Gandhi Kutir',
'Sickon Circle',
'Ashapura Mata Mandir',
'Umabhavan',
'Vishnu Nagar',
'Piyush Complex',
'Patrakar Colony BRTS',
'Pandesara',
'Pandesara Industrial Estate',
'Bamroli Khadi',
'Jay Jalaram Industrial Society',
'Bamroli',
'Om Complex',
'Jagdamba Estate',
'Umiya Nagar Industrial Estate',
'Vadod Gaam',
'Ganeshnagar',
'G.N. Pandya College',
'Priyanka Township',
'Priyanka Green Park Society',
'Priyanka Gold Society',
'D.I.E.T.',
'Swapna Srusti Residency',
'Reshma Nagar',
'Unn Gam',
'Maulana Azad English School',
'Unn Industrial Estate BRTS',
'Noorani Park Society',
'Noorani Masjid',
'Jilani Nagar',
'Santro Bakery',
'Colourtex Industries',
'Gabheni Road',
'Gabheni Gaam']

route106 = ['Railway Station Terminal',
'Delhi Gate',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',
'Limda Chowk',
'Lalgate / Choutapul',
'Bhagatalav',
'Chowk Bazar',
'Chowk Terminal',
'Makkai Pool',
'Dutch Garden',
'Nanpura Post Office',
'Bahumali',
'Girls Polytechnic',
'Vanita Vishram',
'K.P Commerce College',
'Seventh Day School',
'Adarsh Society',
'St.Xavier’s High School Ghod DoD Road',
'Rangeela Park Ghod DoD Road',
'Tribhuvan Complex Ghod DoD Road',
'Gujarati School Ghod DoD Road',
'Parle Point Ghod DoD Road',
'Jaani Farsaan',
'Sushrut Hospital',
'Sargam Shopping Centre',
'Icchanath Mahadev Temple',
'S.V.N.I.T. BRTS',
'Kargil Chowk BRTS',
'Piplod BRTS',
'Bharti Maiya School',
'S.D Planets School',
'S.D. Jain School BRTS',
'SNS Square',
'Jolly Residency',
'Someshwara Enclave Vesu Abhva Road',
'Ratna Jyoti Tower Vesu Abhva Road',
'Agam Shopping Vesu Abhva Road',
'Nalanda School Vesu Abhva Road',
'Abhva Gaam']

# route106 = ['Chowk Terminal',
# 'Makkai Pool',
# 'Dutch Garden',
# 'Nanpura Post Office',
# 'Bahumali',
# 'Girls Polytechnic',
# 'Vanita Vishram',
# 'Jawaharlal Nehru Garden',
# 'Police Commissioner Office',
# 'City Civic Centre',
# 'Surat District Court',
# 'V.T Choksi College',
# 'Parle Point',
# 'Jaani Farsaan',
# 'Sushrut Hospital',
# 'Sargam Shopping Centre',
# 'Icchanath Mahadev Temple',
# 'S.V.N.I.T. BRTS',
# 'Kargil Chowk BRTS',
# 'Piplod BRTS',
# 'Lancer’s Army School BRTS',
# 'Goverdhan Nathji Haveli BRTS',
# 'Rundhnath Mahadev Mandir BRTS',
# 'Magdalla ‘T’ Junction BRTS',
# '‘Y’ Junction Dumas Road BRTS',
# 'Magdalla Gam BRTS',
# 'ONGC Colony BRTS',
# 'Magdalla Port',
# 'ABG Shipyard',
# 'Gaviyar Gam',
# 'C.K.Pithawala Engg. College']

route107 = ['Railway Station Terminal',
'Delhi Gate',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',
'Limda Chowk',
'Lalgate / Choutapul',
'Bhagatalav',
'Chowk Bazar',
'Nehru Bridge',
'Adajan GSRTC',
'Adajan Patiya BRTS',
'Swaminarayan Chowk BRTS',
'Bhulka Bhavan',
'Sri Ram Petrol Pump',
'S.M.C. Sports Complex',
'Mahalaxmi Mandir',
'Van Bhavan',
'Shanti Kunj',
'Green Avenue',
'S.M.C. Performing Art Centre',
'L.P. Savani',
'Ekta Nagar',
'Vidhyakunj',
'Hidayat Nagar Police Station',
'Ambedkar Nagar',
'Vrundavan Flats',
'Ugat S.M.C. Water Treatment Plant',
'S.M.C. Botanical Garden',
'Suman Nursery',
'Mora Bhagal',
'Jahangirpura Community Hall BRTS',
'Pisad Pumping Station',
'Iskcon Circle',
'Nandanvan Row House',
'Patel Nagar Society',
'Vivekanand College']

route108 = ['Railway Station Terminal',
'Delhi Gate',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',
'Limda Chowk',
'Lalgate / Choutapul',
'Bhagatalav',
'Chowk Bazar',
'Nehru Bridge',
'Adajan GSRTC',
'Shankheshwar Chowk BRTS',
'Navyug College BRTS',
'S.M.C. West Zone Office BRTS',
'Tadwadi BRTS',
'Palanpur Patiya BRTS',
'Ramnagar BRTS',
'Morabhagal BRTS',
'Jahangirpura Community Hall BRTS',
'Pisad Pumping Station',
'Iskcon Circle',
'Nandanvan Row House',
'Patel Nagar Society',
'Saroli Gaam',
'Talad',
'BCA College Masma',
'Masma',
'Ishan Pur',
'Cyanide Chemicals',
'Olpad GIDC',
'Sayan Faata',
'Bilal Masjid Olpad',
'Kasba Mohalla Olpad',
'Olpad Bus Depot',
'Lalwatalaav Olpad']

route112 = ['Railway Station Terminal',
'Patelwadi',
'Gotalawadi',
'Katargam Darwaja BRTS',
'Katargam Police Station',
'Bal Ashram',
'V.N Godhani School',
'Dr. Shyamaprasad Mukharji Lake Garden BRTS',
'Gajera Circle BRTS',
'Pandit Shyamji Krishna Verma Bridge BRTS',
'Amroli Char Rasta',
'Arihant Park',
'Swami Narayan Mandir (BAPS)',
'Ganesh Nagar',
'Chaapra Bhaatha',
'Sita Ram Chowk',
'Vatsalya Villa Variyav',
'SMC Water Works Kosad',
'Kosad Ews H1 BRTS',
'Kosad Ews H2 BRTS',
'Kosad Talaav',
'Kosad Gam']

route116 = ['Railway Station Terminal',
'Delhi Gate',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',
'Bhagal Char Rasta',
'Kot Safil Road',
'Wadi Faliya',
'Gopi Talav Market',
'Talawdi Sagrampura',
'Kshetrapal Mandir',
'Vijay Vallabh Chowk',
'Sharda Vidhya Mandir',
'Sanskar Bhavan',
'Majuragate Civil Hospital',
'Income Tax',
'Kapadia Health Club',
'Rupali Junction BRTS',
'Rupali Canal Junction Bhatar Road',
'Uma Bhavan Bhatar Road',
'Atop Nagar Bhatar Road',
'I.G Desai School Althan Road',
'Althan Tenament',
'Kapadia Wadi Althan Road',
'Shayona Park Althan Road',
'Soham Circle',
'Althan Water Works Junction',
'Megnus Alpine Althan Canal Road',
'Ashirwad Enclave Althan Canal Road',
'Bhagwan Mahavir College',
'Mahila I.T.I',
'Sarsana Gam',
'Khajod Gam']

route116B = ['RAILWAY STATION TERMINAL',
'DELHI GATE',
'MOTI TALKIES',
'MAHIDHARPURA POST OFFICE',
'BHAGAL',
'BHAGAL CHAR RASTA',
'KOT SAFIL ROAD',
'WADI FALIYA',
'GOPI TALAV',
'GOPI TALAV MARKET',
'TALAWDI SAGRAMPURA',
'KSHETRAPAL MANDIR',
'VIJAY VALLABH CHOWK',
'SHARDA SCHOOL',
'SANSKAR BHAVAN',
'MAJURAGATE CIVIL HOSPITAL',
'INCOME TAX',
'KAPADIA HEALTH CLUB',
'RUPALI JUNCTION BRTS',
'RUPALI CANAL JUNCTION BHATAR ROAD',
'UMA BHAVAN BHATAR ROAD',
'ATOP NAGAR BHATAR ROAD',
'I.G DESAI SCHOOL ALTHAN ROAD',
'ALTHAN TENAMENT',
'KAPADIA WADI ALTHAN ROAD',
'SHAYONA PARK ALTHAN ROAD',
'SOHAM CIRCLE',
'ALTHAN WATER WORKS JUNCTION',
'MEGNUS ALPINE ALTHAN CANAL ROAD',
'ASHIRWAD ENCLAVE ALTHAN CANAL ROAD',
'BHAGWAN MAHAVIR COLLEGE',
'SAFAL BUNGALOWS',
'BJ PATEL CRICKET GROUND',
'BHIMRAD GAAM APPROACH',
'MAHILA I.T.I',
'SARSANA GAM',
'KHAJOD GAM']

route117 = ['Railway Station Terminal',
'Linear Bus Stop',
'Golden Point',
'Sahara Darwaja',
'Textile Market',
'Kamela Darwaja',
'Kinnary Cinema',
'Maan Darwaja',
'Sub Jail',
'New Civil Hospital',
'Majura Gate',
'Gandhi College',
'Vanita Vishram Ground',
'Athwagate',
'Anand Mahal Road BRTS',
'Kavi Kalapi Garden',
'Shahi Masjid Adajan Gam',
'Spipa (Surat)',
'Gangeshwar Mandir',
'Green Residency',
'Patel Pragati Mandal',
'Ayodhya Nagari Society',
'BSNL Office',
'Bhagyodaya Society',
'Dindayal Society',
'Palanpur Jakatnaka',
'Sandya Vadan Society',
'Mini Virpur',
'Saitirth',
'Palanpur Shala',
'Palanpur Gam',
'Palanpur Gam Talav']

route118 = ['Railway Station Terminal',
'Ashwanikumar Road',
'Vidhi Bhavan',
'Umiya Chowk',
'Leprosy Hospital',
'Patel Nagar',
'Gaushala Fulpada',
'Ashwanikumar Smashan Gruh',
'Katar Gam GIDC',
'Fulpada Road BRTS',
'Gajera Circle BRTS',
'Pandit Shyamji Krishna Verma Bridge BRTS',
'Amroli Char Rasta',
'Amroli Cross Road',
'Kosad Fire Station BRTS',
'Kosad Housing Board BRTS',
'Kosad Depot BRTS',
'Global Residency',
'Vasvari Lake',
'Vasvari Gaam',
'Gothan Vasvaari Faata',
'Sanskar Industrial Estate',
'Delaad Talaav',
'Delaad Industrial Estate',
'Delaad Patiya',
'Mahavir Complex Delaad Patiya',
'Sahyog Society Sayan',
'D.R.G.D High School Sayan',
'Sayan Railway Station']

route126 = ['Railway Station Terminal',
'Delhi Gate',
'Bhagal',
'Bhagal Char Rasta',
'Kot Safil Road',
'Wadi Faliya',
'Gopi Talav Market',
'Talawdi Sagrampura',
'Kshetrapal Mandir',
'Vijay Vallabh Chowk',
'Sharda Vidhya Mandir',
'Sanskar Bhavan',
'Majuragate Civil Hospital',
'Panjara Pol Ghod DoD Road',
'Karimabad Society Ghod DoD Road',
'St.Xavier’s High School Ghod DoD Road',
'Rangeela Park Ghod DoD Road',
'Tribhuvan Complex Ghod DoD Road',
'Gujarati School Ghod DoD Road',
'Parle Point Ghod DoD Road',
'Shrungar Society City Light Road',
'Science Centre City Light Road',
'Prem Prakruti Chowk City Light Road',
'Siddharth Com. Junction City Light Road',
'Anuvrat Dwar Junction (West) BRTS',
'Centre for Social Studies BRTS',
'V.N.S.G.U. Convention Hall BRTS',
'VNSG University']

route127 = ['Railway Station Terminal',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',
'Limda Chowk',
'Lalgate / Choutapul',
'Bhagatalav',
'Nehru Bridge',
'Adajan GSRTC',
'Shankheshwar Chowk BRTS',
'Ambedkar Trust',
'Amidhara Wadi',
'Ajramar Chowk',
'Sangeet Sarita',
'Nilkamal Society',
'Prime Arcade- Adajan',
'Ganeshkrupa Society',
'New Era School',
'Palanpur Patiya BRTS',
'Pipardiwala School',
'Rander Gaam']

route136 = ['Railway Station Terminal',
'Linear Bus Stop',
'Golden Point',
'Sahara Darwaja',
'Maan Darwaja',
'Sub Jail',
'New Civil Hospital',
'Majura Gate',
'Gandhi College',
'Vanita Vishram Ground',
'Athwagate',
'Vanita Vishram',
'Jawaharlal Nehru Garden',
'Police Commissioner Office',
'City Civic Centre',
'Surat District Court',
'V.T Choksi College',
'Parle Point',
'Jaani Farsaan',
'Sushrut Hospital',
'Sargam Shopping Centre',
'Icchanath Mahadev Temple',
'S.V.N.I.T. BRTS',
'Kargil Chowk BRTS',
'Piplod BRTS',
'Lancer’s Army School BRTS',
'Goverdhan Nathji Haveli BRTS',
'Rundhnath Mahadev Mandir BRTS',
'Magdalla ‘T’ Junction BRTS',
'‘Y’ Junction Dumas Road BRTS',
'Magdalla Gam BRTS',
'ONGC Colony BRTS',
'Magdalla Port',
'Gaviyar Vanta',
'Surat Airport']

route137E = ['Railway Station Terminal',
'Delhi Gate',
'Moti Talkies',
'Mahidharpura Post Office',
'Bhagal',
'Limda Chowk',
'Lalgate / Choutapul',
'Bhagatalav',
'Chowk Bazar',
'Nehru Bridge',
'Adajan GSRTC',
'Shankheshwar Chowk BRTS',
'Navyug College BRTS',
'S.M.C. West Zone Office BRTS',
'Tadwadi BRTS',
'Palanpur Patiya BRTS',
'Ramnagar BRTS',
'Morabhagal BRTS',
'Jahangirpura Community Hall BRTS',
'Pisad Pumping Station',
'Iskcon Circle',
'Iscon Mandir',
'Kurukshetra/Rammadhi',
'Asharam Bapu Ashram',
'Variyav Jakatnaka',
'CJ Patel College',
'GWSSB Variav',
'Western City']

route147 = ['LAMBE HANUMAN TEMPLE',
'RAILWAY STATION TERMINAL',
'DELHI GATE',
'MOTI TALKIES',
'MAHIDHARPURA POST OFFICE',
'BHAGAL',
'LIMDA CHOWK',
'LALGATE/CHOUTAPUL',
'BHAGATALAV',
'CHOWK BAZAR',
'CHOWK TERMINAL',
'MAKKAIPOOL TERMINAL',
'CORPORATION SCHOOL',
'PARAM ROW HOUSE',
'BAPS SWAMINARAYAN SANSTHA',
'BHAGWAN PARK',
'BADRINATH MANDIR',
'BAPS HOSPITAL ADAJAN',
'ADAJAN GAM',
'STAR BAZAAR',
'ADAJAN GAM BRTS',
'TRINITY BUSINESS PARK',
'SAURABH SOCIETY',
'SMC PARTY PLOT PAL',
'STUTI RESIDENCY',
'PAL GAAM',
'GALAXY CIRCLE',
'GALAXY ENCLAVE',
'GREEN CITY',
'GREEN CITY BHATHA APPROACH',
'GREEN CITY BHATHA']

route153 = ['KAPODARA',
'BSNL OFFICE MAMTA PARK',
'SAGAR SOCIETY',
'GOPAL CHOWK',
'RACHANA CIRCLE',
'SANTOSH NAGAR',
'GHANSHYAM NAGAR',
'LAABHESHWAR CHOWK',
'MATAWADI CHOWK',
'VASANT BIKHA NI WADI',
'J.B. DIAMOND',
'LAMBE HANUMAN TEMPLE',
'RAILWAY STATION TERMINAL',
'DELHI GATE',
'MOTI TALKIES',
'MAHIDHARPURA POST OFFICE',
'BHAGAL',
'BHAGAL CHAR RASTA',
'KOT SAFIL ROAD',
'WADI FALIYA',
'GOPI TALAV',
'GOPI TALAV MARKET',
'S.M.C. WATER DEPARTMENT',
'KHWAJA DANA NEW ROAD',
'HIJDAWAD',
'MACHHIWAD',
'MAKKAI POOL',
'DUTCH GARDEN',
'NANPURA POST OFFICE',
'BAHUMALI',
'GIRLS POLYTECHNIC',
'VANITA VISHRAM',
'JAWAHARLAL NEHRU GARDEN',
'POLICE COMMISSIONER OFFICE',
'CITY CIVIC CENTRE',
'SURAT DISTRICT COURT',
'V.T CHOKSI COLLEGE',
'PARLE POINT',
'JAANI FARSAAN',
'SUSHRUT HOSPITAL',
'SARGAM SHOPPING CENTRE',
'ICCHANATH MAHADEV TEMPLE',
'UMRA FOOD PARK',
'UMRA GAAM BRTS',
'UMRA HEALTH CENTRE']

route202J = ['Chowk Bazar',
'Nehru Bridge',
'Furaja Chowk',
'S.M.C. Central Zone Office',
'I.P. Mission School',
'Variyali Bazar Police Chowki',
'Hodi Bungalow',
'Makbara Masjid',
'Sant Jalaram Society',
'Nani Bahucharaji Temple',
'Pandol Police Chowki',
'Akhand Anand College',
'Vaadinath Chowk',
'Gopal Nagar',
'Shree Swaminarayan Mandir',
'Shree Sahjanand Chowk BRTS',
'Bapa Sitaram Chowk BRTS',
'Hare Krishna Circle',
'Radadya Vidhyalaya',
'Sardar Complex',
'Krishnakunj Society',
'Krishna Residency',
'Tapi Society',
'Lakshimikant Ashram',
'Akhand Anand Park Society']

route204 = ['Chowk Terminal',
'Machhiwad',
'Keval Circle',
'Kadarshah Ni Nal',
'Symga School',
'Sharda Vidhya Mandir',
'Sanskar Bhavan',
'New Civil Hospital',
'Sub Jail',
'Maan Darwaja',
'Kinnary Cinema',
'Kamela Darwaja',
'Sai Darshan Market',
'Panchsheel Nagar Anjana',
'Nagar Prathmik School Anjana',
'Samrat Vidhyalaya BRTS',
'Model Town Junction BRTS',
'Model Town Dumbhal',
'Neminath Nagar Dumbhal',
'Vidhata Township Parvat',
'Parvat Gam',
'Silicon Flats Parvat',
'Godadra Canal Junction',
'Jai Jogani Mata Chowk BRTS',
'Shantanu Residency Godadara',
'Khodiyar Residency Godadara',
'Radhe Shyam Society Godadara',
'Shamaldham Row House Godadara',
'Sai Shrusti Residency Godadara']

route206 = ['CHOWK TERMINAL',
'MAKKAI POOL',
'DUTCH GARDEN',
'NANPURA POST OFFICE',
'BAHUMALI',
'GIRLS POLYTECHNIC',
'VANITA VISHRAM',
'JAWAHARLAL NEHRU GARDEN',
'POLICE COMMISSIONER OFFICE',
'CITY CIVIC CENTRE',
'SURAT DISTRICT COURT',
'V.T CHOKSI COLLEGE',
'PARLE POINT',
'JAANI FARSAAN',
'SUSHRUT HOSPITAL',
'SARGAM SHOPPING CENTRE',
'ICCHANATH MAHADEV TEMPLE',
'S.V.N.I.T. BRTS',
'KARGIL CHOWK BRTS',
'PIPLOD BRTS',
"LANCER'S ARMY SCHOOL BRTS",
'GOVERDHAN NATHJI HAVELI BRTS',
'RUNDHNATH MAHADEV MANDIR BRTS',
'MAGDALLAT JUNCTION BRTS',
'Y JUNCTION DUMAS ROAD BRTS',
'MAGDALLA GAM BRTS',
'ONGC COLONY BRTS',
'MAGDALLA PORT',
'ABG SHIPYARD',
'GAVIYAR GAM',
'C.K.PITHAWALA ENG.COLLEGE']

route207E = ['CHOWK TERMINAL',
'MAKKAI POOL',
'SHAKTI NIKETAN MANDIR',
'ADAJAN PATIYA BRTS',
'SIDDIQUI SQUARE',
'JILANI COMPLEX',
'HAMZA APARTMENT',
'ALFESANI SCHOOL',
'MADNI SOCIETY',
'AL AMIN',
'ROYAL HERITAGE',
'ARYA SAMAJ MARG',
'PIPARDIWALA SCHOOL',
'RANDER NAHER COLONY',
'RAMNAGAR BRTS',
'MORABHAGAL BRTS',
'SUBHASH GARDEN',
'SUNDARVAN ROW HOUSE',
'SAMDRASTI PARK',
'VASU PUJYA APARTMENT',
'JANKI RESIDENCY',
'VAISHNODEVI HEIGHTS',
'SASHANK PARK SOCIETY',
'VAISHNODEVI TOWNSHIP',
'VAISHNODEVI SKY']

route209J = ['Chowk Terminal',
'Machhiwad',
'Hijdawad',
'Khwaja Dana New Road',
'S.M.C. Water Department',
'Navsari Bazar',
'Janta Hospital',
'Rustampura Swimming Pool',
'Udhana Darwaja',
'Maan Darwaja',
'Kinnary Cinema',
'Halpati Colony',
'Bhathena Canal Junction',
'Siddhi Vinayak Temple',
'Khodiyarnagar',
'L.N. Park Society',
'Udhana GIDC Mahatma Gandhi Road',
'Udhana GIDC Road No.3',
'ROAD No. 3 UDHANA UDHYOG NAGAR CHAR RASTA',
'Udhana Road No.6 Junction',
'S.M.C. Sankul',
'Umiya Nagar',
'Laxminagar Society',
'Dindoli Gam',
'Jitesh Park Society',
'Millenium Park',
'Vrukshlaxmi Society']

route212J = ['Chowk Terminal',
'Chowk Bazar',
'Nehru Bridge',
'Furaja Chowk',
'S.M.C. Central Zone Office',
'I.P. Mission School',
'Variyali Bazar Police Chowki',
'Hodi Bungalow',
'Katargam Darwaja',
'Katargam Police Station',
'Bal Ashram',
'V.N Godhani School',
'Dr. Shyamaprasad Mukharji Lake Garden BRTS',
'Gajera Circle BRTS',
'Pandit Shyamji Krishna Verma Bridge BRTS',
'Amroli Char Rasta',
'Mahavir Dham 2',
'Mahavir Heights',
'Abhishek Township',
'Kosad Talaav',
'Kosad Ews H2 BRTS',
'Kosad Ews H1 BRTS',
'SMC Water Works Kosad',
'Vatsalya Villa Variyav',
'Sita Ram Chowk']

route213 = ['DABHOLI GAAM',
'PRAMUKH YOG APARTMENT DABHOLI',
'SILVER STONE HOMES DABHOLI',
'SARJAN AVENUE APARTMENT',
'KANTHARIYA HANUMAN CHOWK',
'KANTHARIYA HANUMAN TEMPLE',
'RAJ LAXMI HEIGHTS',
'SMC HALL SINGANPORE',
'SINGANPORE VEGETABLE MARKET',
'SINGANPORE CIRCLE',
'AASHIRWAD DOCTOR HOUSE',
'JKP NAGAR SOCIETY',
'SNEH NAGAR SOCIETY',
'KATARGAM',
'KATARGAM FIRE STATION',
'BALASHRAM CHAR RASTA',
'KIRAN HOSPITAL',
'ALKAPURI CIRCLE',
'BHAVANI CIRCLE',
'RAMNAGAR SOCIETY',
'SARDAR SMRUTI BHAVAN',
'SARDAR CHOWK',
'MAANGADH CHOWK BRTS',
'BARODA PRISTAGE BRTS',
'SHRIMAD VALLABHACHARYA CHOWK BRTS',
'D.G.V.C.L. URJA SADAN BRTS',
'SAINATH SOCIETY KAPODARA',
'NILKANTH SOCIETY KAPODARA',
'RASHMI KIRAN APARTMENT',
'SKY LARK COMPLEX KAPODARA',
'MAMTA PARK SOCIETY',
'LAXMINAGAR CHOWK',
'BHAGWATI SOCIETY',
'ANUPAM BUSINESS HUB',
'YOGI CHOWK',
'CITY CIVIC CENTRE YOGI',
'MAHAVIR CHOWK',
'SHYAM DHAM CHOWK SIMADA',
'SHYAM SUNDAR APARTMENT',
'SWAGAT SOCIETY BRTS',
'BAPA SITARAM CHOWK YOGI NAGAR',
'GURUKUM SCHOOL SARTHANA',
'BHAGWAN NAGAR SARTHANA',
'SIMADA VARIGRUH',
'SARTHANA NAKA',
'PURUSHOTTAM NAGAR BRTS']

route216B = ['Chowk Terminal',
'Makkai Pool',
'Dutch Garden',
'Nanpura Post Office',
'Bahumali',
'Girls Polytechnic',
'Vanita Vishram',
'Jawaharlal Nehru Garden',
'Police Commissioner Office',
'City Civic Centre',
'Surat District Court',
'V.T Choksi College',
'Parle Point',
'Jaani Farsaan',
'Sushrut Hospital',
'Sargam Shopping Centre',
'Icchanath Mahadev Temple',
'S.V.N.I.T. BRTS',
'Kargil Chowk BRTS',
'Piplod BRTS',
'Lancer’s Army School BRTS',
'Goverdhan Nathji Haveli BRTS',
'Rundhnath Mahadev Mandir BRTS',
'Magdalla ‘T’ Junction BRTS',
'‘Y’ Junction Dumas Road BRTS',
'Magdalla Gam BRTS',
'ONGC Colony BRTS',
'Magdalla Port',
'Gaviyar Vanta',
'Surat Airport',
'Dumas Kuvada',
'Victoria Palm',
'Bhimpore Faata',
'Kunj Gali',
'Dumas Langar']

route216K = ['Chowk Terminal',
'Makkai Pool',
'Dutch Garden',
'Nanpura Post Office',
'Bahumali',
'Girls Polytechnic',
'Vanita Vishram',
'Jawaharlal Nehru Garden',
'Police Commissioner Office',
'City Civic Centre',
'Surat District Court',
'V.T Choksi College',
'Parle Point',
'Jaani Farsaan',
'Sushrut Hospital',
'Sargam Shopping Centre',
'Icchanath Mahadev Temple',
'S.V.N.I.T. BRTS',
'Kargil Chowk BRTS',
'Piplod BRTS',
'Lancer’s Army School BRTS',
'Goverdhan Nathji Haveli BRTS',
'Rundhnath Mahadev Mandir BRTS',
'Magdalla ‘T’ Junction BRTS',
'‘Y’ Junction Dumas Road BRTS',
'Magdalla Gam BRTS',
'ONGC Colony BRTS',
'Magdalla Port',
'Gaviyar Vanta',
'Surat Airport',
'Dumas Kuvada',
'Agashi Mata Nu Mandir',
'Parsiwad',
'Kaadi Faliya Dumas',
'Moti Bajar Dumas',
'Nani Bajar Dumas',
'Maha Lakshmi Temple',
'Arogya Kendra',
'Bapuji Ni Wadi',
'Sultanabad Aambawadi',
'Sultanabad',
'Dumas Langar']

route217 = ['Makkai Pool',
'Chowk Terminal',
'Chowk Bazar',
'Nehru Bridge',
'Adajan GSRTC',
'Shankheshwar Chowk BRTS',
'Ambedkar Trust',
'Amidhara Wadi',
'Ajramar Chowk',
'Children Park Adajan',
'Shalidhadra Residency',
'Prime Arcade- Adajan',
'Jyotindra Dave Garden',
'Honey Park Cross Road',
'Sai Square',
'L.P Savani Vidhyabhavan',
'Western City',
'Shantvan Row House',
'Royal Platinum',
'Mini Virpur Temple',
'Utran Station(Start)',
'Tapash Nagar',
'SMC Staff Quarters',
'Raj Harmony',
'Anand Villa',
'South Gujarat Medical College']

route226J = ['Kosad Gam',
'Korivad Kosad',
'Shahjanand Apartment',
'Seven Star Residency',
'Maruti Dham Society',
'Hari Siddhi Apartment',
'Krishna Nagar Society',
'Mahavir Dhaam Society',
'Sreepal Nagar Society',
'Amroli Char Rasta',
'Pandit Shyamji Krishna Verma Bridge BRTS',
'Gajera Circle BRTS',
'Dr. Shyamaprasad Mukharji Lake Garden BRTS',
'Jalsa Theatre',
'Kiran Hospital',
'Sagar Industrial Estate',
'Venus Estate',
'Parin Gems',
'Katargam Darwaja BRTS',
'Katargam Darwaja',
'Hodi Bungalow',
'Variyali Bazar Police Chowki',
'I.P. Mission School',
'S.M.C. Central Zone Office',
'Furaja Chowk',
'Chowk Bazar',
'Chowk Terminal',
'Makkai Pool',
'Dutch Garden',
'Nanpura Post Office',
'Bahumali',
'Girls Polytechnic',
'Athwagate',
'Vanita Vishram',
'Jawaharlal Nehru Garden',
'Police Commissioner Office',
'City Civic Centre',
'Surat District Court',
'Parle Point',
'Jaani Farsaan',
'Sushrut Hospital',
'Sargam Shopping Centre',
'Icchanath Mahadev Temple',
'S.V.N.I.T. BRTS',
'Kargil Chowk BRTS',
'SMC Night Food Bazaar',
'Bhagyalaxmi Society',
'Saraswati Nagar',
'Piplod Main Road',
'Someshwar Junction BRTS',
'VNSG University']

route254 = ['Suman Darshan',
'Sharda Vidhya Mandir',
'Singanpore S.T.P',
'Trilok Society',
'Akhand Anand College',
'Pandol Police Chowki',
'Nani Bahucharaji Temple',
'Sant Jalaram Society',
'Makbara Masjid',
'Jilani Bridge Approach Katargam',
'Katargam Darwaja BRT',
'Gotalawadi',
'Patelwadi',
'Lal Darwaja',
'Railway Station Terminal',
'Linear Bus Stop',
'Golden Point',
'Sahara Darwaja',
'Textile Market',
'Kamela Darwaja',
'Sai Darshan Market',
'Panchsheel Nagar Anjana',
'Nagar Prathmik School Anjana',
'Anjana Health Centre',
'Azad Chowk',
'Mithikhadi Ward Office',
'Limbayat Health Centre',
'Shivaji Nagar',
'Nilgiri Circle',
'Shree Nathji Society Godadara',
'Ram Nagar Godadara',
'Hari Darshan Society Godadara',
'Godadara School',
'Godadara Gam',
'Shamaldham Row House Godadara',
'Sai Shrusti Residency Godadara',
'Man Sarovar Society',
'Arvind Nagar',
'Shyam Dham Society Godadara',
'Sai Darshan Society Godadara',
'Samrat Industries 1 Godadara',
'Jigneshnagar Godadara',
'Mangal Pandey Hall Godadara']

route302 = ['KHARWARNAGAR BRTS',
'UDHANA DARWAJA BRTS',
'UDHANA DARWAJA',
'RUSTAMPURA SWIMMING POOL',
'JANTA HOSPITAL',
'NAVSARI BAZAR',
'GOPI TALAV MARKET',
'GOPI TALAV',
'WADI FALIYA',
'KOT SAFIL ROAD',
'BHAGAL CHAR RASTA',
'BHAJIWALI POL',
'KASKIWAD',
'SAIYEDPURA VEGETABLE MARKET',
'PUMPING CHAR RASTA',
'HODI BUNGALOW',
'MAKBARA MASJID',
'SANT JALARAM SOCIETY',
'NANI BAHUCHARAJI TEMPLE',
'PANDOL POLICE CHOWKI',
'AKHAND ANAND COLLEGE',
'VAADINATH CHOWK',
'GOPAL NAGAR',
'SHREE SWAMINARAYAN MANDIR',
'GAYATRI MANDIR DABHOLI CLUSTER',
'KAILASH NAGAR DABHOLI',
'SHREE KUNJ SOCIETY',
'SAHJANAND ESTATE DABHOLI',
'SARDAR PATEL SOCIETY DABHOLI',
'SILVERSTONE RESIDENCY',
'OM HERITAGE DABHOLI',
'SWARAJ HEIGHTS DABHOLI',
'DABHOLI GAAM APPROACH']

route302V = ['KHARWARNAGAR BRTS',
'UDHANA DARWAJA BRTS',
'UDHANA DARWAJA',
'RUSTAMPURA SWIMMING POOL',
'JANTA HOSPITAL',
'NAVSARI BAZAR',
'GOPI TALAV MARKET',
'GOPI TALAV',
'WADI FALIYA',
'KOT SAFIL ROAD',
'BHAGAL CHAR RASTA',
'BHAJIWALI POL',
'KASKIWAD',
'SAIYEDPURA VEGETABLE MARKET',
'PUMPING CHAR RASTA',
'HODI BUNGALOW',
'MAKBARA MASJID',
'SANT JALARAM SOCIETY',
'NANI BAHUCHARAJI TEMPLE',
'PANDOL POLICE CHOWKI',
'AKHAND ANAND COLLEGE',
'VAADINATH CHOWK',
'GOPAL NAGAR',
'SHREE SWAMINARAYAN MANDIR',
'DABHOLI CHAR RASTA',
'PRAMUKH SWAMY CHOWK',
'SMC HEALTH CLUB',
'NANI VED',
'SWAMI NARAYAN GURUKUL',
'MOTI VED DARGAH',
'MOTI VED']

route305 = ['Kharwarnagar BRTS',
'Satyanagar BRTS',
'SMC South Zone Office',
'Jhansi Ki Rani Garden',
'Gayatri Society',
'Ashanagar Soiety',
'Veer Savarkar Circle',
'Shiv Bhakti Apartment',
'SMC Community Hall Udhana',
'Chikuwadi BRTS',
'Bhagirath Apartment',
'KV Hagrenad Road',
'Bhagyalaxmi Prints',
'Maakrupa Chemical Industries Ganeshnagar',
'Vadod Gaam',
'Ganesh Nagar Pandesara',
'Priyanka Township',
'Priyanka Green Park Society',
'Priyanka Gold Society',
'Someshwar Nagar 1',
'Bhestan Garden',
'Bhestan City Bus Depot',
'Bhestan',
'Unn Naka BRTS',
'Unn Industrial Estate BRTS']

route402 = ['Puna Canal BRTS',
'Amazia Amusement Park BRTS',
'Shree Sant Kheteshwar Circle / Parvat Patiya BRTS',
'AAI Mata Road',
'Raghuvir Business Hub',
'J.T. Nagar',
'Archana Char Rasta',
'Renuka Bhavan',
'Nandaalay Haveli',
'Bombay Market',
'Khaadi Mohalla Shaala',
'Bhagat Singh Garden',
'Vasant Bikha Ni Wadi',
'J.B. Diamond',
'Lambe Hanuman Temple',
'Railway Station Terminal',
'Railway Parcel Office',
'I.C. Gandhi School',
'Sumul Dairy',
'Alkapuri Circle',
'Kiran Hospital',
'Katargam BRT',
'Dr. Shyamaprasad Mukharji Lake Garden BRTS',
'Gajera Circle BRTS',
'Pandit Shyamji Krishna Verma Bridge BRTS',
'Amroli Char Rasta']

route403 = ['SMC Ward Office Limbayat',
'Sanjay Nagar Circle',
'Sanjay Nagar Limbayat',
'Sahajanand Society Limbayat',
'Silicon Flats Parvat',
'Parvat Gam',
'Vidhata Township Parvat',
'Neminath Nagar Dumbhal',
'Model Town Dumbhal',
'Parvat Patiya Junction BRTS',
'Amazia Amusement Park BRTS',
'Sitanagar BRTS',
# 'Sita Nagar',
'Punagam Sarkari Mandli',
'Puna Talav',
'Shaarda Vidhya Mandir',
'Kargil Chowk Puna',
'Thakordwar Society',
'Bhagwati Society',
'Anupam Business Hub',
'Yogi Chowk',
'City Civic Centre Yogi',
'Mahavir Chowk',
'Varacha Chowpati F.O.B',
'Tapovan Circle',
'Nana Varachha Vari Gruh BRTS',
'Maharana Pratap Garden (Chowpati) BRTS',
'Nana Varachha Police Station BRTS',
'Sarthana Nature Park BRTS',
'Anmol Park Society',
'Sankalp Residency']

route410 = ['UTRAN LAKE GARDEN',
'DGVCL MOTA VARACHHA',
'SANTOSA HEIGHTS',
'OPERA CITY',
'SLOK RESIDENCY',
'MAHARAJA KRUSHNAKUMAR SCHOOL',
'ROYAL SQUARE',
'UTRAN POWER HOUSE',
'SAMATA NAGAR',
'MOTA VARACHHA PUMPING STATION',
'APPLE HEIGHTS',
'SUDAMA CHOWK',
'MOTA VARACHHA FIRE STATION',
'MOTA VARACHHA WARD OFFICE',
'MOTA VARACHHA PRATHMIK SCHOOL',
'MOTA VARACHHA LAKE',
'SEWAGE PUMPING MOTA VARACHHA',
'RAJHANS TOWER',
'LAJAMANI CHOWK',
'SAVJIKORAT BRIDGE',
'NATVAR NAGAR',
'SARTHANA NATURE PARK BRTS',
'SARTHANA NAKA',
'SIMADA VARIGRUH',
'VRAJ CHOWK',
'VRAJVILLA SOCIETY SHYAMNAGAR',
'SIMADA GAM',
'PATEL PARK',
'YOGI NAGAR BRTS',
'RAGHUKUL RESIDENCY',
'RADHE PARK',
'SAVALIYA CIRCLE',
'VRUNDAVAN SOCIETY PUNA',
'PRAMUKHCHHAYA',
'BALAJI RESIDENCY',
'BHAGWATI SOCIETY',
'LAXMINAGAR CHOWK',
'BSNL OFFICE MAMTA PARK',
'SAGAR SOCIETY',
'GOPAL CHOWK',
'RACHANA SOCIETY',
'SHREE SWAMI DAYANAND SARASWATI BRIDGE',
'SILVER PALACE',
'COMMUNITY HALL UTRAN',
'OMKAR ROW HOUSE',
'UTRAN LAKE GARDEN']

route504 = ['Amazia Amusement Park BRTS',
'Puna Canal BRTS',
'Magob Gam BRTS',
'Parvat Patiya Junction BRTS',
'Model Town Dumbhal',
'Dumbhal Fire Station',
'Narayan Industries Limbayat',
'Nageshwar Temple',
'Sanjay Nagar Limbayat',
'Sahajanand Society Limbayat',
'Godadra Canal Junction',
'Jai Jogani Mata Chowk BRTS',
'Aaspas Dada Temple BRTS',
'Mangal Pandey Hall BRTS',
'Maharana Pratap Bridge / Sai Baba Temple, Dindoli BRTS',
'Dindoli Gam',
'Mark Point Dindoli',
'Shreenath Residency',
'Karadva Gam',
'Bhestan Ews Housing',
'Unn',
'Unn Naka BRTS',
'Maulana Azad English School',
'Unn Gam',
'Reshma Nagar',
'Swapna Srusti Residency',
'Bhestan Garden']

route506 = ['Vesu Gaam',
'SDJain School Vesu',
'Suraj Mandal Jain Temple',
'Vatsalya Bungalows',
'Someshwar Junction BRTS',
'VNSG University',
'V.N.S.G.U. Convention Hall BRTS',
'Centre for Social Studies BRTS',
'Anuvrat Dwar Junction (West) BRTS',
'Chandramani Society Udhana Magdalla Road',
'Brieadliner Circle Udhana Magdalla Road',
'Vishal Society Udhana Magdalla Road',
'Bhatar Flyover Udhana Magdalla Road',
'Ishwar Nagar Udhana Magdalla Road',
'Gandhikutir Junction Udhana Magdalla Road',
'Navjivan Circle Udhana Magdalla Road',
'Somnath Society Udhana Magdalla Road',
'Sosyo Circle Udhana Magdalla Road',
'Khatodara Water Works',
'Khatodara Police Station',
'Kharwarnagar BRTS',
'Satyanagar BRTS',
'Udhana Teen Rasta BRTS',
'Mastannagar',
'Laxminagar',
'Udhana Udhyog Nagar',
'S.M.C. Sankul'
'Umiya Nagar',
'Laxminagar Society',
'Dindoli Gam',
'Ghardi Mata Mandir',
'Shivalik Square',
'Sunrise Vidyalay Dindoli']

route658 = ['Adajan GSRTC',
'Dhanmora / Adajan Patiya BRTS',
'Swaminarayan Chowk BRTS',
'Anand Mahal Road BRTS',
'Adajan Gam BRTS',
'Jagdishchandra Bose Garden',
'Sanjeev Kumar Auditorium BRTS',
'Pal R.T.O. BRTS',
'Pal Patiya',
'Bhatha Gaam',
'Weal Park Industries',
'Icchapor Gaam Faata',
'Panchvati Garden Icchapor',
'Icchapor Lake',
'Hotel Excellency Icchapor',
'Icchapor Town',
'ONGC Road Junction',
'Kribhco Nagar',
'Railway Colony',
'NTPC',
'Gujarat Gas Company Ltd. Mora',
'Mora Teen Rasta',
'Mora Char Rasta']

route706 = ['Iskcon Circle',
'Pisad Pumping Station',
'Jahangirpura Community Hall BRTS',
'Mora Bhagal',
'S.M.C. Sports Complex',
'Sri Ram Petrol Pump',
'Bhulka Bhavan',
'Athwagate',
'Vanita Vishram',
'Jawaharlal Nehru Garden',
'Police Commissioner Office',
'City Civic Centre',
'Surat District Court',
'V.T Choksi College',
'Parle Point',
'Shrungar Society City Light Road',
'Science Centre City Light Road',
'Prem Prakruti Chowk City Light Road',
'Siddharth Com. Junction City Light Road',
'Anuvrat Dwar Junction (West) BRTS',
'Centre for Social Studies BRTS',
'V.N.S.G.U. Convention Hall BRTS',
'V.N.S.G. University']

route716 = ['B R Park',
'Ankur Park Society',
'Jahangirpura Housing',
'SMC Library Jahangirpura',
'Shree Darshan Society',
'Jahangirpura Community Hall BRTS',
'Morabhagal BRTS',
'Devashish Nagar Mora Bhagal',
'Shreenathaji Haveli Ramnagar',
'Shri Ravishankar Maharaj School',
'DGVCL GEB Office Palanpur',
'Housing Board Palanpur',
'Palanpur Patiya Circle',
'Bhagyodaya Society',
'Dindayal Society',
'Palanpur Jakatnaka Circle',
'Vidhyakunj',
'Ekta Nagar',
'L.P. Savani',
'S.M.C. Performing Art Centre',
'Green Avenue',
'Trinity Business Park',
'Adajan Gam BRTS',
'Star Bazaar',
'Surat District Court',
'City Civic Centre',
'Police Lines',
'Athwa Pumping Station',
'Narmad Central Library',
'St.Xavier’s High School Ghod DoD Road',
'Mira Nagar Society',
'Jamna Nagar Society',
'Trimurti Apartment',
'Vivekanand Garden',
'Jivkor Nagar Bhatar',
'Sanjivani Circle Bhatar',
'Bhatar Flyover Udhana Magdalla Road',
'Vishal Society Udhana Magdalla Road',
'Breadliner Circle Udhana Magdalla Road',
'Giridhardwar Soc Althan Canal Road',
'Indralok Bunglow Althan Canal Road',
'Chinagate Road Althan Canal Road',
'Althan Community Hall',
'Soham Circle',
'Althan Water Works Junction',
'Shyam Mandir BRTS',
'E Space Bharthana VIP Road',
'Offira Shopping VIP Road',
'Maniba Party Plot VIP Road',
'Canal Junction VIP Road',
'Balaji Farm VIP Road',
'Ratna Jyoti Tower VIP Road',
'Shri Sarjan Palace VIP Road',
'Vastugram VIP Road',
'Nandini Flat VIP Road',
'Gail India LTD VIP Road']

route903 = ['Shree Gnanjyoti Vidhyalay',
'Pasodara Gaam',
'Chehar Mata Temple',
'Shakun Valley Residency',
'Kathodara Gaam',
'SK Park Society Kathodara',
'Khadsad Gaam',
'Godhpur Township',
'NC Thakkar School',
'Diva Farm',
'VT Nagar Road',
'Purushottam Nagar BRTS',
'Sarthana Nature Park BRTS',
'SMVS Swaminarayan Temple BRTS',
'Swagat Society BRTS',
'Siddharth Nagar Society',
'Yogi Nagar Society',
'Yodi Darshan Society',
'City Centre Puna Gaam',
'Shiv Dhara Heights',
'Satyam Residency Puna Gaam']